// Code generated by gengo:table DO NOT EDIT.
package order

import (
	sqlbuilder "github.com/octohelm/storage/pkg/sqlbuilder"
	modelscoped "github.com/octohelm/storage/pkg/sqlbuilder/modelscoped"
	nullable "github.com/octohelm/storage/pkg/sqltype/nullable"
	sqltypetime "github.com/octohelm/storage/pkg/sqltype/time"

	orderv1 "github.com/octohelm/objectkind/internal/example/pkg/apis/order/v1"
	productv1 "github.com/octohelm/objectkind/internal/example/pkg/apis/product/v1"
)

func (Order) TableName() string {
	return "t_order"
}

func (Order) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

func (Order) Indexes() sqlbuilder.Indexes {
	return sqlbuilder.Indexes{
		"i_state": []string{
			"State",
		},
	}
}

func init() {
	T.Add(OrderT)
}

func (Order) GetKind() string {
	return "Order"
}

func (tableOrder) New() sqlbuilder.Model {
	return &Order{}
}

type tableOrder struct {
	modelscoped.Table[Order]

	I indexesOfOrder

	// id
	ID modelscoped.TypedColumn[Order, orderv1.OrderID]
	// 名称
	Name modelscoped.TypedColumn[Order, string]
	// 描述
	Description modelscoped.TypedColumn[Order, nullable.Text]
	// 创建时间
	CreatedAt modelscoped.TypedColumn[Order, sqltypetime.Timestamp]
	// 更新时间
	UpdatedAt modelscoped.TypedColumn[Order, sqltypetime.Timestamp]

	State modelscoped.TypedColumn[Order, orderv1.OrderState]

	TotalAmount modelscoped.TypedColumn[Order, int]
}

type indexesOfOrder struct {
	Primary modelscoped.Key[Order]
}

var OrderT = &tableOrder{
	Table: modelscoped.FromModel[Order](),

	ID:          modelscoped.CastTypedColumn[Order, orderv1.OrderID](modelscoped.FromModel[Order]().F("ID")),
	Name:        modelscoped.CastTypedColumn[Order, string](modelscoped.FromModel[Order]().F("Name")),
	Description: modelscoped.CastTypedColumn[Order, nullable.Text](modelscoped.FromModel[Order]().F("Description")),
	CreatedAt:   modelscoped.CastTypedColumn[Order, sqltypetime.Timestamp](modelscoped.FromModel[Order]().F("CreatedAt")),
	UpdatedAt:   modelscoped.CastTypedColumn[Order, sqltypetime.Timestamp](modelscoped.FromModel[Order]().F("UpdatedAt")),
	State:       modelscoped.CastTypedColumn[Order, orderv1.OrderState](modelscoped.FromModel[Order]().F("State")),
	TotalAmount: modelscoped.CastTypedColumn[Order, int](modelscoped.FromModel[Order]().F("TotalAmount")),

	I: indexesOfOrder{
		Primary: modelscoped.FromModel[Order]().MK("primary"),
	},
}

func (OrderItem) TableName() string {
	return "t_order_item"
}

func (OrderItem) PrimaryKey() []string {
	return []string{
		"ID",
	}
}

func (OrderItem) UniqueIndexes() sqlbuilder.Indexes {
	return sqlbuilder.Indexes{
		"i_order_item": []string{
			"OrderID",
			"SkuID",
		},
	}
}

func (OrderItem) Indexes() sqlbuilder.Indexes {
	return sqlbuilder.Indexes{
		"i_order_id": []string{
			"OrderID",
		},
	}
}

func init() {
	T.Add(OrderItemT)
}

func (OrderItem) GetKind() string {
	return "OrderItem"
}

func (tableOrderItem) New() sqlbuilder.Model {
	return &OrderItem{}
}

type tableOrderItem struct {
	modelscoped.Table[OrderItem]

	I indexesOfOrderItem

	// id
	ID modelscoped.TypedColumn[OrderItem, orderv1.OrderItemID]
	// 名称
	Name modelscoped.TypedColumn[OrderItem, string]
	// 描述
	Description modelscoped.TypedColumn[OrderItem, nullable.Text]
	// 创建时间
	CreatedAt modelscoped.TypedColumn[OrderItem, sqltypetime.Timestamp]
	// 更新时间
	UpdatedAt modelscoped.TypedColumn[OrderItem, sqltypetime.Timestamp]

	OrderID modelscoped.TypedColumn[OrderItem, orderv1.OrderID]

	SkuID modelscoped.TypedColumn[OrderItem, productv1.SkuID]

	Quantity modelscoped.TypedColumn[OrderItem, int64]

	TotalPrice modelscoped.TypedColumn[OrderItem, float64]

	DiscountAmount modelscoped.TypedColumn[OrderItem, float64]

	FinalPrice modelscoped.TypedColumn[OrderItem, float64]
}

type indexesOfOrderItem struct {
	Primary    modelscoped.Key[OrderItem]
	IOrderItem modelscoped.Key[OrderItem]
}

var OrderItemT = &tableOrderItem{
	Table: modelscoped.FromModel[OrderItem](),

	ID:             modelscoped.CastTypedColumn[OrderItem, orderv1.OrderItemID](modelscoped.FromModel[OrderItem]().F("ID")),
	Name:           modelscoped.CastTypedColumn[OrderItem, string](modelscoped.FromModel[OrderItem]().F("Name")),
	Description:    modelscoped.CastTypedColumn[OrderItem, nullable.Text](modelscoped.FromModel[OrderItem]().F("Description")),
	CreatedAt:      modelscoped.CastTypedColumn[OrderItem, sqltypetime.Timestamp](modelscoped.FromModel[OrderItem]().F("CreatedAt")),
	UpdatedAt:      modelscoped.CastTypedColumn[OrderItem, sqltypetime.Timestamp](modelscoped.FromModel[OrderItem]().F("UpdatedAt")),
	OrderID:        modelscoped.CastTypedColumn[OrderItem, orderv1.OrderID](modelscoped.FromModel[OrderItem]().F("OrderID")),
	SkuID:          modelscoped.CastTypedColumn[OrderItem, productv1.SkuID](modelscoped.FromModel[OrderItem]().F("SkuID")),
	Quantity:       modelscoped.CastTypedColumn[OrderItem, int64](modelscoped.FromModel[OrderItem]().F("Quantity")),
	TotalPrice:     modelscoped.CastTypedColumn[OrderItem, float64](modelscoped.FromModel[OrderItem]().F("TotalPrice")),
	DiscountAmount: modelscoped.CastTypedColumn[OrderItem, float64](modelscoped.FromModel[OrderItem]().F("DiscountAmount")),
	FinalPrice:     modelscoped.CastTypedColumn[OrderItem, float64](modelscoped.FromModel[OrderItem]().F("FinalPrice")),

	I: indexesOfOrderItem{
		Primary:    modelscoped.FromModel[OrderItem]().MK("primary"),
		IOrderItem: modelscoped.FromModel[OrderItem]().MK("i_order_item"),
	},
}
