// Code generated by gengo:runtimedoc DO NOT EDIT.
package order

func (v *Order) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "State":
			return []string{}, true
		case "TotalAmount":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(&v.Resource, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v *OrderItem) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrderID":
			return []string{}, true
		case "SkuID":
			return []string{}, true
		case "Quantity":
			return []string{}, true
		case "TotalPrice":
			return []string{}, true
		case "DiscountAmount":
			return []string{}, true
		case "FinalPrice":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(&v.Resource, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
