// Code generated by gengo:filterop DO NOT EDIT.
package filter

import (
	filter "github.com/octohelm/storage/pkg/filter"
	sqlbuilder "github.com/octohelm/storage/pkg/sqlbuilder"
	sqlpipe "github.com/octohelm/storage/pkg/sqlpipe"
	sqlpipefilter "github.com/octohelm/storage/pkg/sqlpipe/filter"

	order "github.com/octohelm/objectkind/internal/example/domain/order"
	orderv1 "github.com/octohelm/objectkind/internal/example/pkg/apis/order/v1"
	productv1 "github.com/octohelm/objectkind/internal/example/pkg/apis/product/v1"
)

type OrderByID struct {
	// 通过 id 筛选
	ID *filter.Filter[orderv1.OrderID] `name:"order~id,omitzero" in:"query"`
}

func (f *OrderByID) OperatorType() sqlpipe.OperatorType {
	return sqlpipe.OperatorFilter
}

func (f *OrderByID) Next(src sqlpipe.Source[order.Order]) sqlpipe.Source[order.Order] {
	return src.Pipe(sqlpipefilter.AsWhere(order.OrderT.ID, f.ID))
}

type OrderSortByID struct{}

func (f *OrderSortByID) Name() string {
	return "order~id"
}

func (f *OrderSortByID) Label() string {
	return "id"
}

func (f *OrderSortByID) Sort(src sqlpipe.Source[order.Order], sortBy func(col sqlbuilder.Column) sqlpipe.SourceOperator[order.Order]) sqlpipe.Source[order.Order] {
	return src.Pipe(sortBy(order.OrderT.ID))
}

type OrderByState struct {
	State *filter.Filter[orderv1.OrderState] `name:"order~state,omitzero" in:"query"`
}

func (f *OrderByState) OperatorType() sqlpipe.OperatorType {
	return sqlpipe.OperatorFilter
}

func (f *OrderByState) Next(src sqlpipe.Source[order.Order]) sqlpipe.Source[order.Order] {
	return src.Pipe(sqlpipefilter.AsWhere(order.OrderT.State, f.State))
}

type OrderItemByID struct {
	// 通过 id 筛选
	ID *filter.Filter[orderv1.OrderItemID] `name:"order-item~id,omitzero" in:"query"`
}

func (f *OrderItemByID) OperatorType() sqlpipe.OperatorType {
	return sqlpipe.OperatorFilter
}

func (f *OrderItemByID) Next(src sqlpipe.Source[order.OrderItem]) sqlpipe.Source[order.OrderItem] {
	return src.Pipe(sqlpipefilter.AsWhere(order.OrderItemT.ID, f.ID))
}

type OrderItemSortByID struct{}

func (f *OrderItemSortByID) Name() string {
	return "order-item~id"
}

func (f *OrderItemSortByID) Label() string {
	return "id"
}

func (f *OrderItemSortByID) Sort(src sqlpipe.Source[order.OrderItem], sortBy func(col sqlbuilder.Column) sqlpipe.SourceOperator[order.OrderItem]) sqlpipe.Source[order.OrderItem] {
	return src.Pipe(sortBy(order.OrderItemT.ID))
}

type OrderItemByOrderID struct {
	OrderID *filter.Filter[orderv1.OrderID] `name:"order-item~orderID,omitzero" in:"query"`
}

func (f *OrderItemByOrderID) OperatorType() sqlpipe.OperatorType {
	return sqlpipe.OperatorFilter
}

func (f *OrderItemByOrderID) Next(src sqlpipe.Source[order.OrderItem]) sqlpipe.Source[order.OrderItem] {
	return src.Pipe(sqlpipefilter.AsWhere(order.OrderItemT.OrderID, f.OrderID))
}

type OrderItemBySkuID struct {
	SkuID *filter.Filter[productv1.SkuID] `name:"order-item~skuID,omitzero" in:"query"`
}

func (f *OrderItemBySkuID) OperatorType() sqlpipe.OperatorType {
	return sqlpipe.OperatorFilter
}

func (f *OrderItemBySkuID) Next(src sqlpipe.Source[order.OrderItem]) sqlpipe.Source[order.OrderItem] {
	return src.Pipe(sqlpipefilter.AsWhere(order.OrderItemT.SkuID, f.SkuID))
}
