/*
Package schema GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package schema

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *GroupKind) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Kind":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *GroupVersion) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Version":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *GroupVersionKind) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Version":
			return []string{}, true
		case "Kind":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*ObjectMapping) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
