// Code generated by gengo:runtimedoc DO NOT EDIT.
package service

func (v *OrderService) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Products":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.OrderRepository, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.OrderItemRepository, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
