// Code generated by gengo:injectable DO NOT EDIT.
package service

import (
	context "context"
)

type contextOrderService struct{}

func OrderServiceFromContext(ctx context.Context) (*OrderService, bool) {
	if v, ok := ctx.Value(contextOrderService{}).(*OrderService); ok {
		return v, true
	}
	return nil, false
}

func OrderServiceInjectContext(ctx context.Context, tpe *OrderService) context.Context {
	return context.WithValue(ctx, contextOrderService{}, tpe)
}

func (p *OrderService) InjectContext(ctx context.Context) context.Context {
	ctx = p.Products.InjectContext(ctx)

	return OrderServiceInjectContext(ctx, p)
}

func (v *OrderService) Init(ctx context.Context) error {
	if err := v.OrderRepository.Init(ctx); err != nil {
		return err
	}
	if err := v.OrderItemRepository.Init(ctx); err != nil {
		return err
	}
	if err := v.Products.Init(ctx); err != nil {
		return err
	}

	return nil
}
