// Code generated by gengo:injectable DO NOT EDIT.
package sidecar

import (
	context "context"
	fmt "fmt"

	orderservice "github.com/octohelm/objectkind/internal/example/domain/order/service"
)

func (v *OrderExpirer) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	if err := v.Agent.Init(ctx); err != nil {
		return err
	}

	if err := v.afterInit(ctx); err != nil {
		return err
	}

	return nil
}
