// Code generated by gengo:runtimedoc DO NOT EDIT.
package sidecar

func (*Duration) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"是 sidecar 场景下用于 flag/配置解析的时间长度包装。",
	}, true
}

func (v *OrderExpirer) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Period":
			return []string{}, true
		case "TTL":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"定期关闭超过阈值仍未支付的订单。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
