// Code generated by gengo:injectable DO NOT EDIT.
package order

import (
	context "context"
	fmt "fmt"

	orderservice "github.com/octohelm/objectkind/internal/example/domain/order/service"
)

func (v *CancelOrderByID) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	return nil
}

func (v *CompleteOrderByID) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	return nil
}

func (v *CreateOrder) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	return nil
}

func (v *GetOrderByID) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	return nil
}

func (v *ListOrder) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	return nil
}

func (v *PayOrderByID) Init(ctx context.Context) error {
	if value, ok := orderservice.OrderServiceFromContext(ctx); ok {
		v.orderService = value
	} else {
		return fmt.Errorf("missing provider %T.orderService", v)
	}

	return nil
}
