// Code generated by gengo:runtimedoc DO NOT EDIT.
package v1

func (v *Codable[Code]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Code":
			return []string{
				"编码",
			}, true
		}

		return nil, false
	}
	return []string{
		"通过编码标识的资源基础结构",
	}, true
}

func (v *CodableObject[ID, Code]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Object, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Codable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"编码资源对象，包含完整元数据、数字 ID 与编码",
	}, true
}

func (v *CodableReference[O, Code]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.TypeMeta, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Codable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"编码资源引用，包含类型信息与编码",
	}, true
}

func (v *CodableRequest[O, Code]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.TypeMeta, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Describer, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Codable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"编码请求结构，包含类型、描述与编码",
	}, true
}

func (v *CodableResponse[O, ID, Code]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Response, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Codable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"编码响应结构，包含完整元数据、数字 ID 与编码",
	}, true
}

func (v *Describer) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"名称",
			}, true
		case "Description":
			return []string{
				"描述",
			}, true
		case "Annotations":
			return []string{
				"其他注解",
			}, true

		}

		return nil, false
	}
	return []string{
		"资源名称、描述与注解信息",
	}, true
}

func (v *GroupKind) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Kind":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"由 Group 和 Kind 组成的类型标识",
	}, true
}

func (v *GroupVersion) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Version":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"由 Group 和 Version 组成的版本标识",
	}, true
}

func (v *GroupVersionKind) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Group":
			return []string{}, true
		case "Version":
			return []string{}, true
		case "Kind":
			return []string{}, true

		}

		return nil, false
	}
	return []string{
		"由 Group、Version 和 Kind 组成的完整资源标识",
	}, true
}

func (v *Identifiable[ID]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{
				"资源 id",
			}, true
		}

		return nil, false
	}
	return []string{
		"通过数字 ID 标识的资源基础结构",
	}, true
}

func (v *List[T]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Items":
			return []string{
				"列表",
			}, true
		case "Total":
			return []string{
				"总数",
			}, true

		}

		return nil, false
	}
	return []string{
		"泛型资源列表，包含条目与总数",
	}, true
}

func (v *Metadata) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.TypeMeta, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Describer, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.OperationTimestamps, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"资源元数据组合，包含类型、描述与操作时间戳",
	}, true
}

func (v *Object[ID]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Metadata, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Identifiable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"标准资源对象，包含完整元数据与数字 ID",
	}, true
}

func (v *ObjectReference[O, ID]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.TypeMeta, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Identifiable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"资源引用，包含类型信息与数字 ID",
	}, true
}

func (v *OperationTimestamps) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreationTimestamp":
			return []string{
				"创建时间",
			}, true
		case "ModificationTimestamp":
			return []string{
				"更新时间",
			}, true

		}

		return nil, false
	}
	return []string{
		"操作时间戳，记录资源的创建与修改时间",
	}, true
}

func (v *Pager) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Offset":
			return []string{
				"分页偏移",
			}, true
		case "Limit":
			return []string{
				"分页数",
			}, true

		}

		return nil, false
	}
	return []string{
		"分页",
	}, true
}

func (v *Request[O]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.TypeMeta, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Describer, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"通用请求结构，包含类型与描述信息",
	}, true
}

func (v *Response[O, ID]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		}
		if doc, ok := runtimeDoc(&v.Metadata, "", names...); ok {
			return doc, ok
		}
		if doc, ok := runtimeDoc(&v.Identifiable, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"通用响应结构，包含完整元数据与数字 ID",
	}, true
}

func (v *TypeMeta) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Kind":
			return []string{
				"资源类型",
			}, true
		case "APIVersion":
			return []string{
				"资源类型版本",
			}, true

		}

		return nil, false
	}
	return []string{
		"资源类型与版本元数据",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
