// Code generated by gengo:injectable DO NOT EDIT.
package main

import (
	context "context"
)

func (v *APIServer) Init(ctx context.Context) error {
	if err := v.beforeInit(ctx); err != nil {
		return err
	}
	if err := v.Server.Init(ctx); err != nil {
		return err
	}

	return nil
}

type contextDatabase struct{}

func DatabaseFromContext(ctx context.Context) (*Database, bool) {
	if v, ok := ctx.Value(contextDatabase{}).(*Database); ok {
		return v, true
	}
	return nil, false
}

func DatabaseInjectContext(ctx context.Context, tpe *Database) context.Context {
	return context.WithValue(ctx, contextDatabase{}, tpe)
}

func (p *Database) InjectContext(ctx context.Context) context.Context {
	ctx = p.Database.InjectContext(ctx)

	return DatabaseInjectContext(ctx, p)
}

func (v *Database) Init(ctx context.Context) error {
	if err := v.Database.Init(ctx); err != nil {
		return err
	}

	return nil
}
