// Code generated by gengo:injectable DO NOT EDIT.
package service

import (
	context "context"
)

type contextProductService struct{}

func ProductServiceFromContext(ctx context.Context) (*ProductService, bool) {
	if v, ok := ctx.Value(contextProductService{}).(*ProductService); ok {
		return v, true
	}
	return nil, false
}

func ProductServiceInjectContext(ctx context.Context, tpe *ProductService) context.Context {
	return context.WithValue(ctx, contextProductService{}, tpe)
}

func (p *ProductService) InjectContext(ctx context.Context) context.Context {
	return ProductServiceInjectContext(ctx, p)
}

func (v *ProductService) Init(ctx context.Context) error {
	if err := v.ProductRepository.Init(ctx); err != nil {
		return err
	}
	if err := v.SkuRepository.Init(ctx); err != nil {
		return err
	}

	return nil
}
