// Code generated by gengo:runtimedoc DO NOT EDIT.
package product

func (v *Product) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "State":
			return []string{}, true
		}
		if doc, ok := runtimeDoc(&v.Resource, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (v *Sku) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ProductID":
			return []string{
				"所属产品",
			}, true
		case "Price":
			return []string{
				"单价",
			}, true
		case "Currency":
			return []string{
				"货币单位",
			}, true
		case "Annotations":
			return []string{
				"其他属性",
			}, true

		}
		if doc, ok := runtimeDoc(&v.CodableResource, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
