// Code generated by gengo:operator DO NOT EDIT.
package product

import (
	courier "github.com/octohelm/courier/pkg/courier"
	courierhttp "github.com/octohelm/courier/pkg/courierhttp"
	statuserror "github.com/octohelm/courier/pkg/statuserror"

	productv1 "github.com/octohelm/objectkind/internal/example/pkg/apis/product/v1"
)

func init() {
	R.Register(courier.NewRouter(&CreateProduct{}))
}

func (CreateProduct) ResponseContent() any {
	return new(productv1.Product)
}

func (CreateProduct) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&CreateSkuByProductID{}))
}

func (CreateSkuByProductID) ResponseContent() any {
	return new(productv1.Sku)
}

func (CreateSkuByProductID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrSkuNotFound](),
			Message: "商品规格不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&DeleteProductByID{}))
}

func (DeleteProductByID) ResponseContent() any {
	return new(courierhttp.NoContent)
}

func (DeleteProductByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&DeleteSkuByID{}))
}

func (DeleteSkuByID) ResponseContent() any {
	return new(courierhttp.NoContent)
}

func (DeleteSkuByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrSkuNotFound](),
			Message: "商品规格不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&GetProductByID{}))
}

func (GetProductByID) ResponseContent() any {
	return new(productv1.Product)
}

func (GetProductByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&GetSkuByID{}))
}

func (GetSkuByID) ResponseContent() any {
	return new(productv1.Sku)
}

func (GetSkuByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrSkuNotFound](),
			Message: "商品规格不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&ListProduct{}))
}

func (ListProduct) ResponseContent() any {
	return new(productv1.ProductList)
}

func init() {
	R.Register(courier.NewRouter(&ListSkuByProductID{}))
}

func (ListSkuByProductID) ResponseContent() any {
	return new(productv1.SkuList)
}

func (ListSkuByProductID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&PublishProductByID{}))
}

func (PublishProductByID) ResponseContent() any {
	return new(productv1.Product)
}

func (PublishProductByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductStateConflict](),
			Message: "商品当前状态不允许执行该操作",
			Status:  409,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&UnpublishProductByID{}))
}

func (UnpublishProductByID) ResponseContent() any {
	return new(productv1.Product)
}

func (UnpublishProductByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductStateConflict](),
			Message: "商品当前状态不允许执行该操作",
			Status:  409,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&UpdateProductByID{}))
}

func (UpdateProductByID) ResponseContent() any {
	return new(productv1.Product)
}

func (UpdateProductByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrProductNotFound](),
			Message: "商品不存在",
			Status:  404,
		},
	}
}

func init() {
	R.Register(courier.NewRouter(&UpdateSkuByID{}))
}

func (UpdateSkuByID) ResponseContent() any {
	return new(productv1.Sku)
}

func (UpdateSkuByID) ResponseErrors() []error {
	return []error{
		&statuserror.Descriptor{
			Code:    statuserror.ErrCodeFor[productv1.ErrSkuNotFound](),
			Message: "商品规格不存在",
			Status:  404,
		},
	}
}
