// Code generated by gengo:injectable DO NOT EDIT.
package product

import (
	context "context"
	fmt "fmt"

	productservice "github.com/octohelm/objectkind/internal/example/domain/product/service"
)

func (v *CreateProduct) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *CreateSkuByProductID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *DeleteProductByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *DeleteSkuByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *GetProductByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *GetSkuByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *ListProduct) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *ListSkuByProductID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *PublishProductByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *UnpublishProductByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *UpdateProductByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}

func (v *UpdateSkuByID) Init(ctx context.Context) error {
	if value, ok := productservice.ProductServiceFromContext(ctx); ok {
		v.productService = value
	} else {
		return fmt.Errorf("missing provider %T.productService", v)
	}

	return nil
}
