// Code generated by gengo:enum DO NOT EDIT.
package v1

import (
	bytes "bytes"
	driver "database/sql/driver"
	errors "errors"
	fmt "fmt"

	enumeration "github.com/octohelm/enumeration/pkg/enumeration"
	pkgscanner "github.com/octohelm/enumeration/pkg/scanner"
)

var InvalidOrderState = errors.New("invalid OrderState")

func (OrderState) EnumValues() []any {
	return []any{
		ORDER_STATE__CREATED, ORDER_STATE__PAID, ORDER_STATE__CANCELED, ORDER_STATE__COMPLETED,
	}
}

func (v OrderState) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

func (v *OrderState) UnmarshalText(data []byte) error {
	vv, err := ParseOrderStateFromString(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

func ParseOrderStateFromString(s string) (OrderState, error) {
	switch s {
	case "CREATED":
		return ORDER_STATE__CREATED, nil
	case "PAID":
		return ORDER_STATE__PAID, nil
	case "CANCELED":
		return ORDER_STATE__CANCELED, nil
	case "COMPLETED":
		return ORDER_STATE__COMPLETED, nil

	default:
		var i OrderState
		_, err := fmt.Sscanf(s, "UNKNOWN_%d", &i)
		if err == nil {
			return i, nil
		}
		return ORDER_STATE_UNKNOWN, InvalidOrderState
	}
}

func (v OrderState) IsZero() bool {
	return v == ORDER_STATE_UNKNOWN
}

func (v OrderState) String() string {
	switch v {
	case ORDER_STATE__CREATED:
		return "CREATED"
	case ORDER_STATE__PAID:
		return "PAID"
	case ORDER_STATE__CANCELED:
		return "CANCELED"
	case ORDER_STATE__COMPLETED:
		return "COMPLETED"
	case ORDER_STATE_UNKNOWN:
		return "UNKNOWN"

	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

func ParseOrderStateLabelString(label string) (OrderState, error) {
	switch label {
	case "已创建":
		return ORDER_STATE__CREATED, nil
	case "已支付":
		return ORDER_STATE__PAID, nil
	case "已取消":
		return ORDER_STATE__CANCELED, nil
	case "已完成":
		return ORDER_STATE__COMPLETED, nil

	default:
		return ORDER_STATE_UNKNOWN, InvalidOrderState
	}
}

func (v OrderState) Label() string {
	switch v {
	case ORDER_STATE__CREATED:
		return "已创建"
	case ORDER_STATE__PAID:
		return "已支付"
	case ORDER_STATE__CANCELED:
		return "已取消"
	case ORDER_STATE__COMPLETED:
		return "已完成"

	default:
		return fmt.Sprint(v)
	}
}

func (v OrderState) Value() (driver.Value, error) {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}
	return int64(v) + int64(offset), nil
}

func (v *OrderState) Scan(src any) error {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}

	i, err := pkgscanner.ScanIntEnumStringer(src, offset)
	if err != nil {
		return err
	}
	*v = OrderState(i)
	return nil
}
