// Code generated by gengo:uintstr DO NOT EDIT.
package v1

import (
	strconv "strconv"
)

func (id *OrderID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}
	v, err := strconv.ParseUint(str, 10, 64)
	if err != nil {
		return err
	}
	*id = OrderID(v)
	return nil
}

func (id OrderID) MarshalText() (text []byte, err error) {
	if id == 0 {
		return nil, nil
	}
	return []byte(strconv.FormatUint(uint64(id), 10)), nil
}

func (id OrderID) String() string {
	return strconv.FormatUint(uint64(id), 10)
}

func (id *OrderItemID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}
	v, err := strconv.ParseUint(str, 10, 64)
	if err != nil {
		return err
	}
	*id = OrderItemID(v)
	return nil
}

func (id OrderItemID) MarshalText() (text []byte, err error) {
	if id == 0 {
		return nil, nil
	}
	return []byte(strconv.FormatUint(uint64(id), 10)), nil
}

func (id OrderItemID) String() string {
	return strconv.FormatUint(uint64(id), 10)
}
