// Code generated by gengo:runtimedoc DO NOT EDIT.
package compose

func (v *Annotatable) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Annotations":
			return []string{
				"其他标注",
			}, true
		}

		return nil, false
	}
	return []string{
		"可注解类型，组合 Annotations 并提供读写便利方法。",
	}, true
}

func (*Annotations) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"键值对注解，实现 sql.Scanner 与 driver.Valuer，以 JSON 文本形式存储。",
	}, true
}

func (v *CodableResource[ID, Code]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Code":
			return []string{
				"编码",
				"人类可读编码",
			}, true
		}
		if doc, ok := runtimeDoc(&v.Resource, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"带编码的泛型资源类型，在 Resource 基础上增加人类可读编码字段。",
	}, true
}

func (v *CreationTimestamp) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true
		}

		return nil, false
	}
	return []string{
		"创建时间追踪，提供 MarkCreatedAt 方法。",
	}, true
}

func (v *DeletionTimestamp) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "DeletedAt":
			return []string{
				"删除时间",
			}, true
		}

		return nil, false
	}
	return []string{
		"删除时间追踪，实现 sqltype.WithSoftDelete 接口。",
	}, true
}

func (v *ModificationTimestamp) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "UpdatedAt":
			return []string{
				"更新时间",
			}, true
		}

		return nil, false
	}
	return []string{
		"修改时间追踪，提供 MarkModifiedAt 方法。",
	}, true
}

func (v *Rel[ID]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{
				"自增 id",
			}, true
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true

		}

		return nil, false
	}
	return []string{
		"泛型关联表类型，只包含自增主键与创建时间，用于多对多映射。",
	}, true
}

func (v *Resource[ID]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{
				"id",
			}, true
		case "Name":
			return []string{
				"名称",
			}, true
		case "Description":
			return []string{
				"描述",
			}, true
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true
		case "UpdatedAt":
			return []string{
				"更新时间",
			}, true

		}

		return nil, false
	}
	return []string{
		"通用资源类型，组合 ID、名称、描述与创建/更新时间字段。",
	}, true
}

func (v *Revision[ID, Digest]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{
				"id",
			}, true
		case "Digest":
			return []string{
				"摘要",
			}, true
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true

		}

		return nil, false
	}
	return []string{
		"泛型版本记录类型，用于记录每次变更的快照摘要。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
