/*
Package pager GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package pager

func (v *Pager[M]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Offset":
			return []string{
				"分页偏移",
			}, true
		case "Limit":
			return []string{
				"分页数",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *RawPager) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Offset":
			return []string{
				"分页偏移",
			}, true
		case "Limit":
			return []string{
				"分页条数",
			}, true

		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
