// Code generated by gengo:injectable DO NOT EDIT.
package repository

import (
	context "context"
)

func (v *OrderItemRepository) Init(ctx context.Context) error {
	if err := v.orderItemID.Init(ctx); err != nil {
		return err
	}

	return nil
}

func (v *OrderRepository) Init(ctx context.Context) error {
	if err := v.orderID.Init(ctx); err != nil {
		return err
	}

	return nil
}
